spring.application.name=Ecommerce

# ================= DATABASE =================
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=YOUR_MY_SQL_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# ================= TWILIO =================
twilio.account.sid=REAL_SID
twilio.auth.token=REAL_TOKEN

# ?? IMPORTANT: Aa change kariyu chhe (tamaro Twilio number mukyu)
twilio.whatsapp.from=whatsapp:+14155238886
twilio.sms.from=+15824443247

# ================= EMAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com

# ? IMPORTANT: Aa app password hovvu joie (normal password nai chale)
spring.mail.password=REAL_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================= ADMIN =================
app.admin.phone=+911234567890
app.admin.email=admin@example.com